### PR TITLE
Array count check - No username and password caused crash

### PR DESCRIPTION
**Pull request by nicolaspierre1990**

### CODE REVIEW

**Comment by mcintyre321** [comment]
Great to see you're using this tool - please let me know if you need anything further, or if you have any feedback on it. Thanks!

**Comment by nicolaspierre1990** [comment]
Could do with a few more additions. Shall i add features to the repo and we make it together ? :)

**Comment by mcintyre321** [comment]
If you submit PRs I will endeavour to pull them in ASAP. It might be worth checking with me if you are going to do anything controversial, or that would break/change backward compatibility for anyone who is currently using the tool though.

FYI I just changed the return type on main back to integer - this lets the windows shell pick up errors correctly (see linked article in Program.cs)

**Comment by nicolaspierre1990** [comment]
I'll do that !

**Pull request merged**
